server:
  port: 8080
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.zzq.book.dao
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
